name: lassoesm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.0=py310h06a4308_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py310h5eee18b_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=24.2=py310h06a4308_0
  - pandas=2.2.3=py310h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.7.1=py310h6a678d5_1
  - pyqt6-sip=13.9.1=py310h5eee18b_1
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2024.1=py310h06a4308_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.15.3=py310h525edd1_0
  - setuptools=72.1.0=py310h06a4308_0
  - sip=6.10.0=py310h6a678d5_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.5=py310h5eee18b_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.2
    - aiosignal==1.3.2
    - async-timeout==5.0.1
    - attrs==25.3.0
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - datasets==3.6.0
    - dill==0.3.8
    - filelock==3.18.0
    - frozenlist==1.6.0
    - fsspec==2025.3.0
    - hf-xet==1.1.2
    - huggingface-hub==0.32.2
    - idna==3.10
    - jinja2==3.1.6
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - multidict==6.4.4
    - multiprocess==0.70.16
    - networkx==3.4.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.9.41
    - nvidia-nvtx-cu12==12.1.105
    - propcache==0.3.1
    - pyarrow==20.0.0
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - sympy==1.14.0
    - tokenizers==0.15.2
    - torch==2.1.0
    - tqdm==4.67.1
    - transformers==4.35.2
    - triton==2.1.0
    - typing-extensions==4.13.2
    - urllib3==2.4.0
    - xxhash==3.5.0
    - yarl==1.20.0
prefix: /home/xuenan/anaconda3/envs/lassoesm
